In [30]:
#Q4
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error,r2_score


In [19]:
data=pd.read_csv('./advertising/Advertising Budget and Sales.csv')
print(data.columns)

Index(['Unnamed: 0', 'TV Ad Budget ($)', 'Radio Ad Budget ($)',
       'Newspaper Ad Budget ($)', 'Sales ($)'],
      dtype='object')


In [20]:
x=data[['Radio Ad Budget ($)','TV Ad Budget ($)']]
y=data['Sales ($)']
print(x,y)

     Radio Ad Budget ($)  TV Ad Budget ($)
0                   37.8             230.1
1                   39.3              44.5
2                   45.9              17.2
3                   41.3             151.5
4                   10.8             180.8
..                   ...               ...
195                  3.7              38.2
196                  4.9              94.2
197                  9.3             177.0
198                 42.0             283.6
199                  8.6             232.1

[200 rows x 2 columns] 0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales ($), Length: 200, dtype: float64


In [22]:
X=np.c_[np.ones(x.shape[0]),x]
print(X)

[[  1.   37.8 230.1]
 [  1.   39.3  44.5]
 [  1.   45.9  17.2]
 [  1.   41.3 151.5]
 [  1.   10.8 180.8]
 [  1.   48.9   8.7]
 [  1.   32.8  57.5]
 [  1.   19.6 120.2]
 [  1.    2.1   8.6]
 [  1.    2.6 199.8]
 [  1.    5.8  66.1]
 [  1.   24.  214.7]
 [  1.   35.1  23.8]
 [  1.    7.6  97.5]
 [  1.   32.9 204.1]
 [  1.   47.7 195.4]
 [  1.   36.6  67.8]
 [  1.   39.6 281.4]
 [  1.   20.5  69.2]
 [  1.   23.9 147.3]
 [  1.   27.7 218.4]
 [  1.    5.1 237.4]
 [  1.   15.9  13.2]
 [  1.   16.9 228.3]
 [  1.   12.6  62.3]
 [  1.    3.5 262.9]
 [  1.   29.3 142.9]
 [  1.   16.7 240.1]
 [  1.   27.1 248.8]
 [  1.   16.   70.6]
 [  1.   28.3 292.9]
 [  1.   17.4 112.9]
 [  1.    1.5  97.2]
 [  1.   20.  265.6]
 [  1.    1.4  95.7]
 [  1.    4.1 290.7]
 [  1.   43.8 266.9]
 [  1.   49.4  74.7]
 [  1.   26.7  43.1]
 [  1.   37.7 228. ]
 [  1.   22.3 202.5]
 [  1.   33.4 177. ]
 [  1.   27.7 293.6]
 [  1.    8.4 206.9]
 [  1.   25.7  25.1]
 [  1.   22.5 175.1]
 [  1.    9.9  89.7]
 [  1.   41.5

In [23]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
print(x_train,x_test)
print(y_train,y_test)

[[  1.   10.6 284.3]
 [  1.   21.  184.9]
 [  1.   17.4 112.9]
 [  1.   35.1  23.8]
 [  1.    4.1 290.7]
 [  1.   16.   19.4]
 [  1.   27.7 293.6]
 [  1.   12.1  18.7]
 [  1.    4.9 134.3]
 [  1.   39.   25.6]
 [  1.    9.6 100.4]
 [  1.    0.   80.2]
 [  1.   18.1 188.4]
 [  1.   33.4 177. ]
 [  1.   36.9 125.7]
 [  1.   20.6 209.6]
 [  1.   29.3 142.9]
 [  1.   43.9 184.9]
 [  1.    4.3 222.4]
 [  1.   38.  241.7]
 [  1.   45.9  17.2]
 [  1.   28.5 120.5]
 [  1.    9.9  89.7]
 [  1.   28.7 191.1]
 [  1.   10.8  75.5]
 [  1.   18.4 193.2]
 [  1.   35.8  85.7]
 [  1.   43.8 266.9]
 [  1.   41.1  39.5]
 [  1.   42.7 261.3]
 [  1.   15.9  13.2]
 [  1.   35.4 193.7]
 [  1.   36.3 296.4]
 [  1.   20.  265.6]
 [  1.   24.  214.7]
 [  1.   35.6 149.7]
 [  1.   18.4 131.7]
 [  1.   32.8  57.5]
 [  1.   16.7 240.1]
 [  1.   26.8 141.3]
 [  1.   10.8 180.8]
 [  1.    1.5  97.2]
 [  1.   33.2 220.5]
 [  1.    1.9 140.3]
 [  1.   26.9 255.4]
 [  1.   14.8  96.2]
 [  1.    5.8  66.1]
 [  1.   15.5

In [33]:
def linear_regression(X, y):
    # Transpose of X
    x_transpose = np.transpose(X)
    
    # Matrix multiplication of X^T * X
    xTx = np.dot(x_transpose, X)
    
    # Inverse of X^T * X
    xTx_inverse = np.linalg.inv(xTx)
    
    # Matrix multiplication of inverse(X^T * X) * X^T
    xtx_inverse_xTranspose = np.dot(xTx_inverse, x_transpose)
    
    # Calculate beta coefficients: beta = (X^T * X)^(-1) * X^T * y
    beta = np.dot(xtx_inverse_xTranspose, y)
    
    return beta

def linear_regression_line(beta):
    print(f"{beta[0]}+{beta[1]}*x1+{beta[2]}*x2")
    
def predictions(X,beta):
    return np.dot(X,beta)

In [36]:
# Calculate beta coefficients
beta = linear_regression(x_train, y_train)

# Print the regression equation
linear_regression_line(beta)

# Make predictions on X_test using the beta coefficients
y_pred = predictions(x_test, beta)

# Print the predicted values
print("Predicted Sales:", y_pred)


2.83761723690517+0.20260565947128442*x1+0.04407736405785017*x2
Predicted Sales: [16.43778963 21.11462413 21.48161733 10.82947123 22.47553785 13.23902536
 21.28797822  7.39171109 13.32928225 15.11419102  9.21015343  6.46961736
 13.86261835  9.13354422  9.41188141 11.91990874  8.85260103 16.26801624
 10.26953764 18.8732391  19.49753509 13.24142966 12.67756515 21.29173445
  7.76318799  5.60096753 20.96017782 11.91537611  9.07191016  8.71874103
 12.17104929 10.04118685 21.61332453 12.43639201 18.02635199 20.28621948
 14.48901992 20.75689534 10.9817875   4.3739138   9.51065505 12.52354331
 10.14692274  8.13646833 13.19720037  5.27101348  9.19116969 14.17248822
  8.60296178 11.77237575 15.76641197 11.69874553 13.12850705 11.06278083
  6.36721238  9.6960804   9.51719197 24.177049    7.77390733 12.25642418]


In [46]:
rmse=root_mean_squared_error(y_test,y_pred)
print(rmse)

r2=r2_score(y_test,y_pred)
print(r2)

print(y_test.values)
print(y_pred)

4.87397292170871
0.12997792345004988
[16.9 22.4 21.4  7.3 24.7 12.6 22.3  8.4 11.5 14.9  9.5  8.7 11.9  5.3
 10.3 11.7  5.5 16.6 11.3 18.9 19.7 12.5 10.9 22.2  9.3  8.1 21.7 13.4
 10.6  5.7 10.6 11.3 23.7  8.7 16.1 20.7 11.6 20.8 11.9  6.9 11.  12.8
 10.1  9.7 11.6  7.6 10.5 14.6 10.4 12.  14.6 11.7  7.2  6.6  9.4 11.
 10.9 25.4  7.6 11.7]
[16.43516959 19.89515687 15.63842426 17.50466888 19.72592613 17.16404487
 18.84653723 11.82564037 10.01557128 14.28636115 14.47319238 10.65969225
 10.66275913 15.67718397  9.85804888 11.16063976 15.57919565 14.30213048
 13.82259419 15.1758516  16.77786465 18.06120856 17.93477263 17.66332
 11.17339571  9.78962136 18.71269557 12.37485199 11.93631906 15.03104545
  9.91675972 13.73740151 20.32458408 19.36499374 12.48781401 16.5857626
 19.34395359 15.91630232 12.37450682  9.69734051 11.02993056 11.22304052
 15.22146132 12.03964378  9.82323107 10.08636153 12.97341675 14.47530312
 10.70211601 15.22098325 19.53565696 10.80801574 20.35252601 17.98322314
  9.4

In [47]:
#Q5
x=data[['Newspaper Ad Budget ($)','TV Ad Budget ($)']]
X=np.c_[np.ones(x.shape[0]),x]
y=data['Sales ($)']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

# Calculate beta coefficients
beta = linear_regression(x_train, y_train)

# Print the regression equation
linear_regression_line(beta)

# Make predictions on X_test using the beta coefficients
y_pred = predictions(x_test, beta)

# Print the predicted values
print("Predicted Sales:", y_pred)

rmse=root_mean_squared_error(y_test,y_pred)
print(rmse)
r2=r2_score(y_test,y_pred)
print(r2)



5.642052219592907+0.054762564960176986*x1+0.04596023218622235*x2
Predicted Sales: [16.04429782 17.51962128 21.46954703  8.65505487 15.94233158 11.97965283
 17.09577232  8.94769502 16.58099746 15.41470967  7.21027718  9.85146545
 21.06359218  6.40500558 13.51018884 15.39212602  8.2447321  15.50142252
 10.88264106 17.15539956 20.25330783 15.00108837  8.04021557 21.13280792
  8.86259455  9.27284353 17.30553649 12.60289073 11.0681349   6.14311956
 15.98587299  9.82465523 18.0692963  11.31455345 20.5693043  16.88002112
  8.32741324 21.4906929  11.32430928  8.0395437  12.2384544  14.12749373
  9.54510426  9.50752962 16.79144024  8.15345649 11.12115726 13.45795941
 12.33332474 10.02501897 11.12545087 14.08271615 10.14909861  8.77152782
  9.96389992 13.30337455  9.72197035 21.76057481  7.47383637 15.04689323]
3.006590307424539
0.6689355450060164
[16.9 22.4 21.4  7.3 24.7 12.6 22.3  8.4 11.5 14.9  9.5  8.7 11.9  5.3
 10.3 11.7  5.5 16.6 11.3 18.9 19.7 12.5 10.9 22.2  9.3  8.1 21.7 13.4
 10.6  5

In [48]:
#Q6
x=data[['Newspaper Ad Budget ($)','Radio Ad Budget ($)']]
X=np.c_[np.ones(x.shape[0]),x]
y=data['Sales ($)']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

# Calculate beta coefficients
beta = linear_regression(x_train, y_train)

# Print the regression equation
linear_regression_line(beta)

# Make predictions on X_test using the beta coefficients
y_pred = predictions(x_test, beta)

# Print the predicted values
print("Predicted Sales:", y_pred)

rmse=root_mean_squared_error(y_test,y_pred)
print(rmse)
r2=r2_score(y_test,y_pred)
print(r2)

print(y_test.values)
print(y_pred)


9.166645818872869+0.009026329868662086*x1+0.2149060419088063*x2
Predicted Sales: [16.43516959 19.89515687 15.63842426 17.50466888 19.72592613 17.16404487
 18.84653723 11.82564037 10.01557128 14.28636115 14.47319238 10.65969225
 10.66275913 15.67718397  9.85804888 11.16063976 15.57919565 14.30213048
 13.82259419 15.1758516  16.77786465 18.06120856 17.93477263 17.66332
 11.17339571  9.78962136 18.71269557 12.37485199 11.93631906 15.03104545
  9.91675972 13.73740151 20.32458408 19.36499374 12.48781401 16.5857626
 19.34395359 15.91630232 12.37450682  9.69734051 11.02993056 11.22304052
 15.22146132 12.03964378  9.82323107 10.08636153 12.97341675 14.47530312
 10.70211601 15.22098325 19.53565696 10.80801574 20.35252601 17.98322314
  9.47216033 10.67413438 12.93648819 18.71931948 13.63970487  9.97207231]
4.87397292170871
0.12997792345004988
[16.9 22.4 21.4  7.3 24.7 12.6 22.3  8.4 11.5 14.9  9.5  8.7 11.9  5.3
 10.3 11.7  5.5 16.6 11.3 18.9 19.7 12.5 10.9 22.2  9.3  8.1 21.7 13.4
 10.6  5.7 10