In [6]:
import pandas as pd
import numpy as np

df=pd.read_csv('./car/CAR DETAILS FROM CAR DEKHO.csv')

print(df)

x=df['year'].values
y=df['selling_price'].values

xBar=np.mean(x)
yBar=np.mean(y)

numerator=np.sum((x-xBar)*(y-yBar))
denominator = np.sum((x-xBar)**2)

b1=numerator/denominator
b0=yBar-(b1*xBar)
y_pred=b0+(b1*x)

print(f"Slope: {b1}")
print(f"Intercept: {b0}")
print(f"y_pred = {b0} + {b1}x")

n=len(y)
rmse=np.sqrt(np.sum((y_pred-y)**2)/n)
print(f"RMSE: {rmse}")
budget=float(input("Enter value:"))
predicted = b0+(b1*budget)
print(predicted)


                                     name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individ

158109.65264084935


In [33]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load the dataset
file_path = './car/Car details v3.csv'  # Replace with your dataset path
df = pd.read_csv(file_path)

# Linear Regression Class using Normal Equation
class LinearRegression:
    def fit(self, X, y):
        X_b = np.c_[np.ones((X.shape[0], 1)), X]  # Add bias term
        self.weights = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

    def predict(self, X):
        X_b = np.c_[np.ones((X.shape[0], 1)), X]  # Add bias term for predictions
        return X_b.dot(self.weights)

    def mean_squared_error(self, y_true, y_pred):
        return np.mean((y_true - y_pred) ** 2)

# Function to split data into training and testing sets
def train_test_split_data(df, target_column, feature_columns):
    X = df[feature_columns].values
    y = df[target_column].values
    return train_test_split(X, y, test_size=0.2, random_state=42)

# Objective 7: Predicting selling prices w.r.t year_bought
print("\nObjective 7: Predicting selling prices w.r.t year_bought")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['year'])

model = LinearRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 8: Predicting selling prices w.r.t km_driven
print("\nObjective 8: Predicting selling prices w.r.t km_driven")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['km_driven'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 9: Predicting selling prices w.r.t transmission (assuming one-hot encoding)
print("\nObjective 9: Predicting selling prices w.r.t transmission")
labelEncoder = LabelEncoder()
df['transmission_encoded'] = labelEncoder.fit_transform(df['transmission'])  # Create a new column for encoded values

X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['transmission_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 10: Predicting selling prices w.r.t owner (assuming one-hot encoding)
print("\nObjective 10: Predicting selling prices w.r.t owner")
df['owner_encoded'] = labelEncoder.fit_transform(df['owner'])  # Create a new column for encoded values

X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['owner_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")


Objective 7: Predicting selling prices w.r.t year_bought
[-1.64584487e+05  6.55275987e+05  8.19248082e+05 -6.12391809e+02
  5.73289940e+05]
[198000 500000 425000 150000 525000]
RMSE: 736815.8042389858

Objective 8: Predicting selling prices w.r.t km_driven
[519441.90787859 -23609.70620059 638808.99582469 489600.13589206
 641793.17302334]
[198000 500000 425000 150000 525000]
RMSE: 782522.9469343919

Objective 9: Predicting selling prices w.r.t transmission
[457374.22733686 457374.22733686 457374.22733686 457374.22733686
 457374.22733686]
[198000 500000 425000 150000 525000]
RMSE: 651549.4889680177

Objective 10: Predicting selling prices w.r.t owner
[154755.91194431 761130.07094948 761130.07094948 457942.9914469
 457942.9914469 ]
[198000 500000 425000 150000 525000]
RMSE: 787709.2505443231


In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load the dataset
file_path = './car/Car details v3.csv'  # Replace with your dataset path
df = pd.read_csv(file_path)

# Linear Regression Class using Normal Equation
class LinearRegression:
    def fit(self, X, y):
        X_b = np.c_[np.ones((X.shape[0], 1)), X]  # Add bias term
        self.weights = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

    def predict(self, X):
        X_b = np.c_[np.ones((X.shape[0], 1)), X]  # Add bias term for predictions
        return X_b.dot(self.weights)

    def mean_squared_error(self, y_true, y_pred):
        return np.mean((y_true - y_pred) ** 2)

# Function to split data into training and testing sets
def train_test_split_data(df, target_column, feature_columns):
    X = df[feature_columns].values
    y = df[target_column].values
    return train_test_split(X, y, test_size=0.2, random_state=42)

# Encode categorical variables
labelEncoder = LabelEncoder()
df['transmission_encoded'] = labelEncoder.fit_transform(df['transmission'])
df['owner_encoded'] = labelEncoder.fit_transform(df['owner'])

# Objective 11: Predicting selling prices w.r.t year_bought and km_driven
print("\nObjective 11: Predicting selling prices w.r.t year_bought and km_driven")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['year', 'km_driven'])

model = LinearRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 12: Predicting selling prices w.r.t year_bought and transmission
print("\nObjective 12: Predicting selling prices w.r.t year_bought and transmission")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['year', 'transmission_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 13: Predicting selling prices w.r.t year_bought and owner
print("\nObjective 13: Predicting selling prices w.r.t year_bought and owner")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['year', 'owner_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 14: Predicting selling prices w.r.t year_bought and owner (duplicate of Objective 13)
print("\nObjective 14: Predicting selling prices w.r.t year_bought and owner")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['year', 'owner_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 15: Predicting selling prices w.r.t km_driven and transmission
print("\nObjective 15: Predicting selling prices w.r.t km_driven and transmission")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['km_driven', 'transmission_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 16: Predicting selling prices w.r.t km_driven and owner
print("\nObjective 16: Predicting selling prices w.r.t km_driven and owner")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['km_driven', 'owner_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 17: Predicting selling prices w.r.t transmission and owner
print("\nObjective 17: Predicting selling prices w.r.t transmission and owner")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['transmission_encoded', 'owner_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")

# Objective 18: Predicting selling prices w.r.t transmission and owner (duplicate of Objective 17)
print("\nObjective 18: Predicting selling prices w.r.t transmission and owner")
X_train, X_test, y_train, y_test = train_test_split_data(df, 'selling_price', ['transmission_encoded', 'owner_encoded'])

model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions[:5])
print(y_test[:5])
rmse = np.sqrt(model.mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse}")


Objective 11: Predicting selling prices w.r.t year_bought and km_driven
[-151002.56709564  472420.898469    808874.65681258   -4683.48430183
  577921.25082148]
[198000 500000 425000 150000 525000]
RMSE: 734733.9642086156

Objective 12: Predicting selling prices w.r.t year_bought and transmission
[-84169.64688878 490410.02503764 605325.95942293  30746.2874965
 432952.05784501]
[198000 500000 425000 150000 525000]
RMSE: 615179.8798638894

Objective 13: Predicting selling prices w.r.t year_bought and owner
[-211808.61739205  675803.33047721  832243.29708144   -2662.59336375
  544877.28975103]
[198000 500000 425000 150000 525000]
RMSE: 736117.0712891711

Objective 14: Predicting selling prices w.r.t year_bought and owner
[-211808.61739205  675803.33047721  832243.29708144   -2662.59336375
  544877.28975103]
[198000 500000 425000 150000 525000]
RMSE: 736117.0712891711

Objective 15: Predicting selling prices w.r.t km_driven and transmission
[403737.66056359 130443.67272386 463809.86481791 