In [4]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,confusion_matrix

In [2]:
data=pd.read_csv('./Iris/Iris.csv')
print(data)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [5]:
X=data[['SepalLengthCm'  ,'SepalWidthCm'  ,'PetalLengthCm' ,'PetalWidthCm']]
print(X)
le=LabelEncoder()
Y=le.fit_transform(data['Species'])
print(Y)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 

In [6]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)
print(X_train,Y_train)
print(X_test,Y_test)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
81             5.5           2.4            3.7           1.0
133            6.3           2.8            5.1           1.5
137            6.4           3.1            5.5           1.8
75             6.6           3.0            4.4           1.4
109            7.2           3.6            6.1           2.5
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[105 rows x 4 columns] [1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2 1 1 2 1 0 1 2 0
 0 1 1 0 2 0 0 1 1 2 1 2 2 1 0 0 2 2 0 0 0 1 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1
 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
     SepalLengthCm

In [7]:
model=SVC(kernel='linear')
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [11]:
#27,28,29,30
# Confusion Matrix
cm = confusion_matrix(Y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Precision Score
precision = precision_score(Y_test, y_pred, average='macro')  # Macro-averaging for multiclass
print("Precision Score:", precision)
# Recall Score
recall = recall_score(Y_test, y_pred, average='macro')
print("Recall Score:", recall)

# Accuracy Score
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy Score:", accuracy)

# F1-Measure
f1 = f1_score(Y_test, y_pred, average='macro')
print("F1-Measure:", f1)


Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Precision Score: 1.0
Recall Score: 1.0
Accuracy Score: 1.0
F1-Measure: 1.0


In [12]:
rbfmodel=SVC(kernel='rbf')
rbfmodel.fit(X_train,Y_train)
y_pred_rbf=rbfmodel.predict(X_test)
print(y_pred_rbf)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [13]:
#31,32,33,34
# Confusion Matrix
cm = confusion_matrix(Y_test, y_pred_rbf)
print("Confusion Matrix:\n", cm)

# Precision Score
precision = precision_score(Y_test, y_pred_rbf, average='macro')  # Macro-averaging for multiclass
print("Precision Score:", precision)
# Recall Score
recall = recall_score(Y_test, y_pred_rbf, average='macro')
print("Recall Score:", recall)

# Accuracy Score
accuracy = accuracy_score(Y_test, y_pred_rbf)
print("Accuracy Score:", accuracy)

# F1-Measure
f1 = f1_score(Y_test, y_pred_rbf, average='macro')
print("F1-Measure:", f1)

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Precision Score: 1.0
Recall Score: 1.0
Accuracy Score: 1.0
F1-Measure: 1.0


In [15]:
#35
from sklearn.tree import DecisionTreeClassifier

decisionTreeModel=DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=2)
decisionTreeModel.fit(X_train,Y_train)
y_pred_decision_tree_gini=decisionTreeModel.predict(X_test)
print(y_pred_decision_tree_gini)

# Evaluate Accuracy
accuracy = accuracy_score(Y_test, y_pred_decision_tree_gini)
print("Accuracy using GINI Index:", accuracy)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
Accuracy using GINI Index: 1.0


In [17]:
#36
from sklearn.tree import DecisionTreeClassifier

decisionTreeModelEntropy=DecisionTreeClassifier(criterion='entropy',max_depth=4,min_samples_split=2)
decisionTreeModelEntropy.fit(X_train,Y_train)
y_pred_decision_tree_entropy=decisionTreeModelEntropy.predict(X_test)
# Evaluate Accuracy
accuracy = accuracy_score(Y_test, y_pred_decision_tree_entropy)
print("Accuracy using Entropy :", accuracy)

Accuracy using Entropy : 1.0


In [23]:
#39
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

model = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=10, random_state=42)
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

# Evaluate Accuracy
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy (Bagging Classifier):", accuracy)


Accuracy (Bagging Classifier): 1.0


In [24]:
#40
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

# Evaluate Accuracy
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy (Random Forest Classifier):", accuracy)


Accuracy (Random Forest Classifier): 1.0


In [25]:
#41
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(n_estimators=100, random_state=42)
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

# Evaluate Accuracy
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy (Gradient Boosting Classifier):", accuracy)


Accuracy (Gradient Boosting Classifier): 1.0


In [27]:
#42
from sklearn.ensemble import AdaBoostClassifier

model = AdaBoostClassifier(n_estimators=100, random_state=42)
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

# Evaluate Accuracy
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy (AdaBoost Classifier):", accuracy)


c:\python\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Accuracy (AdaBoost Classifier): 1.0


In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, log_loss

# Load the Iris dataset
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Step 1: Understand the Dataset
print("Iris Dataset:")
print(df.head())
print("\nClass Distribution:")
print(df['target'].value_counts())

# Step 2: Split the dataset into training and testing sets
X = df[iris.feature_names]
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Build a Decision Tree Classifier with Log Loss criterion
dt_classifier = DecisionTreeClassifier(criterion='log_loss', max_depth=4, min_samples_split=2)
dt_classifier.fit(X_train, y_train)

# Step 4: Make predictions and evaluate the model using Accuracy and Log Loss
y_pred = dt_classifier.predict(X_test)
y_pred_proba = dt_classifier.predict_proba(X_test)

accuracy = accuracy_score(y_test, y_pred)
log_loss_value = log_loss(y_test, y_pred_proba)

print(f"\nDecision Tree Classifier Accuracy: {accuracy:.2f}")
print(f"Decision Tree Classifier Log Loss: {log_loss_value:.2f}")

Iris Dataset:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

Class Distribution:
target
0    50
1    50
2    50
Name: count, dtype: int64

Decision Tree Classifier Accuracy: 1.00
Decision Tree Classifier Log Loss: 0.00


In [2]:
import numpy as np
from sklearn.metrics import accuracy_score

class LogisticRegression:
    def __init__(self, learning_rate=0.01, num_iterations=1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
        self.weights = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        # Initialize weights
        self.weights = np.zeros(n_features)

        # Gradient Descent
        for _ in range(self.num_iterations):
            linear_model = np.dot(X, self.weights)
            y_predicted = self.sigmoid(linear_model)

            # Update weights using gradient descent
            gradient = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            self.weights -= self.learning_rate * gradient

    def predict(self, X):
        linear_model = np.dot(X, self.weights)
        y_predicted_prob = self.sigmoid(linear_model)
        y_predicted_class = [1 if i > 0.5 else 0 for i in y_predicted_prob]
        return np.array(y_predicted_class), y_predicted_prob

# Load the Iris dataset again (or you can use the same data from above)
iris = load_iris()
X = iris.data
y = iris.target

# Convert target to binary for logistic regression (e.g., class 0 vs others)
y_binary = (y == 0).astype(int)  # Change this to classify between any two classes as needed

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

# Step 2: Build a Logistic Regression Classifier from Scratch
log_reg_classifier = LogisticRegression(learning_rate=0.01, num_iterations=10000)
log_reg_classifier.fit(X_train, y_train)

# Step 3: Make predictions and evaluate the model using Accuracy and Log Loss
y_pred_binary, y_pred_proba_binary = log_reg_classifier.predict(X_test)
accuracy_binary = accuracy_score(y_test, y_pred_binary)

# Calculate log loss manually for binary classification predictions
epsilon = 1e-15  # To avoid log(0)
y_pred_proba_binary = np.clip(y_pred_proba_binary, epsilon, 1 - epsilon)  # Clip predictions to avoid log(0)
log_loss_value_binary = -np.mean(y_test * np.log(y_pred_proba_binary) + (1 - y_test) * np.log(1 - y_pred_proba_binary))

print(f"\nLogistic Regression Classifier Accuracy (Binary Classification): {accuracy_binary:.2f}")
print(f"Logistic Regression Classifier Log Loss: {log_loss_value_binary:.2f}")


Logistic Regression Classifier Accuracy (Binary Classification): 1.00
Logistic Regression Classifier Log Loss: 0.01
